### ISSUE TITLE
A modificação não funciona no MSL.

### ISSUE THREAD

**Issue by Balzaral** [altairwei/Stoneshard-CurseScroll#1]
A modificação da erro ao instalar.

**Comment by altairwei** [comment]
Can you turn on log output for MSL inside the settings and copy the logs here?

**Comment by Balzaral** [comment]
De inicio aparece a mensagem no MSL dessa forma: patching failed, cant save. E no registro:
[11:31:59 ERR] Something went wrong
System.ArgumentException: Cannot add the event Create_0 in o_msl_timer since it already exists
   at ModShardLauncher.Msl.AddNewEvent(UndertaleGameObject gameObject, String eventCode, EventType eventType, UInt32 subtype)
[11:31:59 WRN] Patching {Waiting to be patched} for {CurseScroll} {v0.11.2.0}
[11:31:59 ERR] Something went wrong
System.ArgumentException: Cannot add the event Create_0 in o_msl_timer since it already exists
   at ModShardLauncher.Msl.AddNewEvent(UndertaleGameObject gameObject, String eventCode, EventType eventType, UInt32 subtype)
   at ModShardLauncher.LogUtils.InjectLog()
   at ModShardLauncher.ModLoader.PatchFile()
   at ModShardLauncher.Controls.ModInfos.Save_Click(Object sender, EventArgs e)
[11:31:59 INF] Failed patching vanilla

**Comment by altairwei** [comment]
Please start adding mods from the original `data.win` file. ModShardLauncher does not support adding mods to a modded `data.win` file.

**Comment by Balzaral** [comment]
mas quando eu modifico o data.win original ele não vai.

**Comment by Balzaral** [comment]
@altairwei restaurei meua arquivos do jogo os baixando novamente e o erro pesisti olha o registro:
[11:45:22 WRN] Patching {Patching failed} for {CurseScroll} {v0.11.2.0}
[11:45:22 ERR] Something went wrong
System.Exception: Name mismatch
   at UndertaleModLib.Decompiler.Assembler.Assemble(String source, IList`1 funcs, IList`1 vars, IList`1 strg, UndertaleData data) in E:\????MOD??\Repos\UndertaleModTool\UndertaleModLib\Decompiler\Assembler.cs:line 320
   at UndertaleModLib.Decompiler.Assembler.Assemble(String source, UndertaleData data) in E:\????MOD??\Repos\UndertaleModTool\UndertaleModLib\Decompiler\Assembler.cs:line 349
   at ModShardLauncher.Msl.Save(FileEnumerable`1 fe)
   at CurseScroll.CurseScroll.PatchMod()
   at ModShardLauncher.ModLoader.PatchMods()
   at ModShardLauncher.ModLoader.PatchFile()
   at ModShardLauncher.Controls.ModInfos.Save_Click(Object sender, EventArgs e)
[11:45:22 INF] Failed patching vanilla
[11:46:05 INF] Successfully load: C:\Program Files (x86)\Steam\steamapps\common\Stoneshard\data.win.
[11:46:12 INF] Get table: gml_GlobalScript_table_weapons
[11:46:13 INF] Get table: gml_GlobalScript_table_weapons_text
[11:46:13 INF] Get table: gml_GlobalScript_table_weapons
[11:46:13 INF] Get table: gml_GlobalScript_table_armor
[11:46:13 INF] Reading {CurseScroll} built with version v0.11.2.0

**Comment by altairwei** [comment]
What version of MSL are you using?

**Comment by Balzaral** [comment]
MSL-29-v0-11-2-0-1722030102

**Comment by altairwei** [comment]
Try the latest v0.11.3

**Comment by altairwei** [comment]
https://github.com/ModShardTeam/ModShardLauncher/releases

**Comment by Balzaral** [comment]
Esse link não me deixa baixar.

**Comment by Balzaral** [comment]
@altairwei Consegui, obrigado pelo ajuda, resolveu meu problema, vou testar sua modificação e conserteza me diverti muito, muito obrigado. Espero que você continue a desenvolver mais modificação.
